### ISSUE TITLE
Doesn't adjust spacing when added to a panel

### ISSUE THREAD

**Issue by NICHOLAS85** [MarcinOrlowski/html-clock-plasmoid#11]
**What's wrong?**
When I place the widget in a panel (I'm using a latte panel) I am unable to see the full widget. 

**Steps to reproduce the behavior:**
 1. Add the widget to a panel 

**Expected behavior**
The width of the widget to expand to fill the size of the space it takes up

**Runtime environment**
 - HTML Clock version (see About dialog): 1.1.1
 - Plasma version (output of `plasmashell --version`): plasmashell 5.20.5
 - Name and version of OS: (just paste output of `lsb_release -a`):
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        testing
Codename:       bullseye

**Notes**
![image](https://user-images.githubusercontent.com/15698885/105568121-02e95d80-5d05-11eb-9aec-026ff2acc1ae.png)
Red text is HTML Clock, placed between two widgets.

**Comment by MarcinOrlowski** [comment]
Hi, thanks for the report. I believe this is some sort of bug in the widget but I wish to reproduce it. Unfortunately I am apparently too dumb for Latte as I am not sure how you add widgets to it? Any attempt of doing "Add widget..." from Latte's context menu ends up adding such widget to my desktop. Mind giving steps for dummies?

**Comment by NICHOLAS85** [comment]
I currently just drag the widget from the widget selection menu into the panel. When I hover over the panel while holding the widget a small plus symbol appears showing me where the widget will be placed.

**Comment by MarcinOrlowski** [comment]
Thanks. Should be fixed in v1.1.2

**Comment by NICHOLAS85** [comment]
Thanks! I can confirm it's properly displaying now.
