### ISSUE TITLE
{k} placeholder expands to 24 hour format instead of 12

### ISSUE THREAD

**Issue by NICHOLAS85** [MarcinOrlowski/html-clock-plasmoid#14]
**What's wrong?**
Use {k} placeholder and find that it expands to the same value as {h}, a 24-hour format, instead of the expected 12-hour format.

**Runtime environment**
 - HTML Clock version (see About dialog): 1.1.2
 - Plasma version (output of `plasmashell --version`): plasmashell 5.20.5
 - Name and version of OS: (just paste output of `lsb_release -d`): Debian GNU/Linux bullseye/sid
 - If you use non-standard dock (i.e. Latte), put its name: Latte dock

**Comment by MarcinOrlowski** [comment]
Thanks for fixing that.
