### ISSUE TITLE
Tooltip showing date of current boot instead of current date

### ISSUE THREAD

**Issue by noir-Z** [MarcinOrlowski/html-clock-plasmoid#20]
**What's wrong?**
When i hover the clock, the tooltip shows the date of the day i booted the current session instead of the current date.

Here is a screenshot that I just took (26th)
![htmlclock](https://user-images.githubusercontent.com/45096516/105850496-171dab00-5fe2-11eb-8278-08ff0b8d96e8.png)

**Steps to reproduce the behavior:**
 1. Hover the clock

**Expected behavior**
Show today's date

**Runtime environment**
 - 1.1.2
 - Plasma version 5.20.5
 - Name and version of OS: Arch

Edit:
I updated before posting this but i think the update through the "Get new Widgets" dialogue does not get applied until plasmashell is restarted either manually or through reboot.
I will report tomorrow if it still happens with 1.2.0, after a manual restart of plasmashell, it shows the current date.

**Comment by MarcinOrlowski** [comment]
Thanks. I just spotted that moments ago and signed it to file a ticket on myself but you were faster :) That's definitely a bug.
