### ISSUE TITLE
Debian 10 KDE Plasma 5

### ISSUE THREAD

**Issue by Kolychy** [MarcinOrlowski/html-clock-plasmoid#28]
**What's wrong?**
![1](https://user-images.githubusercontent.com/80788248/111376375-cf99ce00-86b8-11eb-816f-1b567f933658.png)
![2](https://user-images.githubusercontent.com/80788248/111376378-d0cafb00-86b8-11eb-8aa0-fe70ce3fc725.png)

**Steps to reproduce the behavior:**
 1. I installed using the built-in Plasma add-on installer
 
**Runtime environment**
 - HTML Clock version: 1.3.0
 - Plasma version: 5.14.5
 - Name and version of OS: Debian GNU/Linux 10 (buster)

**Comment by MarcinOrlowski** [comment]
Seems ancient Plasma Debian provides do not support backtick syntax. That's odd a bit but hey :) Can you please check attached RC build and let me know if it address this issue for you. But **BEFORE** you install RC version, please confirm that v1.3.0's About dialog is also exposing the same issue (which RC also fixes).

**Comment by MarcinOrlowski** [comment]
RC build
