### ISSUE TITLE
Issues with user layout customization

### ISSUE THREAD

**Issue by GaganChandan** [MarcinOrlowski/html-clock-plasmoid#37]
I'm trying to make a custom user layout, but I'm unable to clone a default layout. The clone button shown in the image in the repo simply isn't there (see the attached image).

![Screenshot_20210714_035413](https://user-images.githubusercontent.com/79305438/125558540-e8c07b85-4dc0-4289-80d2-f49aadab10e5.png)

**Comment by GaganChandan** [comment]
Similar to issur #35

**Comment by MarcinOrlowski** [comment]
I am unable to reproduce this issue. What you should see is this:
![Uploading x.png…]()
