### ISSUE TITLE
Calendar View is broken

### ISSUE THREAD

**Issue by noir-Z** [MarcinOrlowski/html-clock-plasmoid#41]
**What's wrong?**
Calendar View is broken

**Steps to reproduce the behavior:**
1. Have Calendar View enabled
2. Click Html Clock

**Expected behavior**
![digitalclock](https://user-images.githubusercontent.com/45096516/145713205-b7c8cde8-a980-4e52-a99e-1236a5608012.png)

**Actual behavior**
![htmlclock](https://user-images.githubusercontent.com/45096516/145713207-9b813ca7-3267-4949-a98a-3c1a38764d14.png)

**Runtime environment**
 - HTML Clock version: 1.6.1
 - Plasma version: 5.23.4
 - Name and version of OS: Arch Linux

**Comment by MarcinOrlowski** [comment]
Fixed in 1.6.2
