### ISSUE TITLE
Fonts and default layout are not being saved

### ISSUE THREAD

**Issue by p0lygun** [MarcinOrlowski/html-clock-plasmoid#46]
**What's wrong?**
Please put a clear and concise description of what the bug is.
there is no option to apply when I change the font in user layout
**Steps to reproduce the behavior:**
 1. Make sure user layout is enabled
 2. Try changing font, 
 3. Button to apply still disabled

**Expected behavior**
It should let me update font

**Runtime environment**
 - HTML Clock version (see About dialog) 1.6.2
 - Plasma version (output of `plasmashell --version`) plasmashell 5.25.3
 - Name and version of OS: (just paste output of `lsb_release -d`) Description:    Arch Linux
 - If you use non-standard dock (i.e. Latte), put its name.

**Notes**
Any additional information that may be helpful diagnosing the problem.
i am trying to make a vertical clock with minutes and seconds on the side, 
my layout 
```html
<body width="100%" height="100%" style="font-family: Sevensegment; font-size: 20px;">

    <span style="font-size:30px; color:#d703fc; font-weight:bold">{kk}</span>
    <span style="font-size:15px; color: #{flip:00:FF}ffffff;">:</span>
    <table>
        <tr>
            <td style="align: center;">
                <span style="font-size:10px; color:#d703fc; font-weight:bold">{ii}</span>
            </td>
        </tr>
        <tr>
            <td style="align: center;">
                <span
                    style="font-size:10px; color:#d703fc; font-weight:bold; float:right;">{ss}</span>
            </td>
        </tr>
    </table>                
</body>
```
result 

![image](https://user-images.githubusercontent.com/22869882/179289786-166bafc1-d1ed-4717-b771-25994c4d2cc2.png)

and the buttons on the user layout are also not showing 

![image](https://user-images.githubusercontent.com/22869882/179289920-cf71e0c9-6213-4e12-b498-5dedc4137356.png)

**Comment by p0lygun** [comment]
Gif to show the error
![bug_report](https://user-images.githubusercontent.com/22869882/179291717-f8f8bbea-599a-462a-871d-738d8425a366.gif)

**Comment by MarcinOrlowski** [comment]
You are confused because version you use is broken and do not expose all the buttons you should see in that layout. Please [upgrade to 1.6.3](https://github.com/MarcinOrlowski/html-clock-plasmoid/releases) that have this fixed. Also please [see docs](https://github.com/MarcinOrlowski/html-clock-plasmoid#user-layout) on how fonts helper is designed to work (it is not altering your layout)
