### ISSUE TITLE
Transparent background?

### ISSUE THREAD

**Issue by zohozer** [MarcinOrlowski/html-clock-plasmoid#56]
I do want to make this applet to have a transparent background and without any borders, just the clock numbers and I can't find anything related into documentation.

Please add an option to remove the background and the borders alltogether.

Best regards.

**Comment by zohozer** [comment]
On the frontpage it is saying:
` Transparent background: by default, widget uses theme provided background color. When this option is checked, widget background is no longer drawn, making it fully transparent. Note: this option is hidden on Plasma 5.19 as it introduces similar feature for the all widgets which is preferred. option to built-in or newer these version.`

But I can't find any option in the applet to check for the "Transparent background".

Please fix this issue.

**Comment by zohozer** [comment]
Nevermind, found a solution. Needs to be in widget edit mode and hower the mouse over the widget, will appear a button on the Top-Left corner that says "Show Background". By clicking-it the background it is removed.

![Remove_Background](https://user-images.githubusercontent.com/5983791/219953578-4e43e265-ec84-43ae-8f93-88aaa9bf81f7.png)

**Comment by MarcinOrlowski** [comment]
Thanks for the follow up. Yes, this is Plasma's feature available since Plasma 5.19.  I am closing this one as there's nothing really to fix. Feel free to reopen if needed.
