### ISSUE TITLE
Incorrect handling of multiple {flip} blocks per single template line

### ISSUE THREAD

**Issue by zohozer** [MarcinOrlowski/html-clock-plasmoid#57]
I do try to make the minutes to blink on every second pass but seems that the {flip} option it is not working properly.

If I do 

`<span style="color: {flip:red:green};">{flip:{ii}:{ii}}</span>`

I get `{fli` displayed on screen instead of the minutes numbers.

How to fix this flipping issue?

**Comment by MarcinOrlowski** [comment]
Thanks for the feedback. There are indeed some oddities in how `flip` works. As far as I can tell the problem shows up when you got more than one `{flip}` in a single text line. That most likely a bug, but it seems the workaround is trivial here - just break your markup into multiple lines so only single `flip` per line remains. In case of your template making it look like this should work that bug around:

```
<span style="color: {flip:red:green};">
{flip:{ii}:{ii}}</span>
```

**Comment by MarcinOrlowski** [comment]
BTW: `{flip:{ii}:{ii}}` is basically `{ii}` (alternating between the same value makes no visible difference), so you can also remove that `{flip}` completely.

**Comment by MarcinOrlowski** [comment]
Debug note: it seems it's not about the `flip` but the how `{}` are handled as you can have single `{flip}` and then some other placeholders in the same line and that bug can show up as well, i.e. `{flip:FOO:BAR} {DDD:U}`

**Comment by MarcinOrlowski** [comment]
Fixed in 1.6.4

**Comment by zohozer** [comment]
Thank you for the fix. I am currently running the 1.6.3 version and seems that it is not upgrading by itself. If I right-click on the clock and press the "Check for update..." button, nothing happens.

I am running SteamOS (Arch distro) on a SteamDeck machine. The discover package manager is up to date with all the software but this plasmoid clock don't seems to update.

**Comment by MarcinOrlowski** [comment]
It would not self update that way anyway but just notify about newer version. Will check why that is not working
