### ISSUE TITLE
{ss} and {s} placeholders not working

### ISSUE THREAD

**Issue by FadeDave77** [MarcinOrlowski/html-clock-plasmoid#7]
Intended behaviour: {ss} and {s} to be reaplaced by current seconds, either prefixed with 0 or not

Actual behaviour: {ss} and {s} stay as plain text in the clock

**Comment by MarcinOrlowski** [comment]
To have `{s}` and `{ss}` working you need v1.1.0 of the widget. Please upgrade: https://github.com/MarcinOrlowski/html-clock-plasmoid/releases/tag/1.1.0

**Comment by FadeDave77** [comment]
I was on version 1.1.0, but the new version 1.1.1 fixed it.

**Comment by MarcinOrlowski** [comment]
That's bit odd. Where you had 1.1.0 from? KDE Store or Github?

**Comment by FadeDave77** [comment]
KDE store, but I updated it using the kde store too, so it definitely is good now.

**Comment by MarcinOrlowski** [comment]
Thanks. Seems I managed to release 1.1.0 broken somehow. Gonna hide that file from store then.

**Comment by MarcinOrlowski** [comment]
Thanks. Seems I managed to release 1.1.0 broken somehow. Gonna hide that file from store then.
