### ISSUE TITLE
Add Google Calendar sync

### ISSUE THREAD

**Issue by Sadi58** [MarcinOrlowski/html-clock-plasmoid#72]
The _EventCalendar_ plasmoid has stopped syncing with _Google Calendar_, but the _Kalendar_ app has this feature now. 
It would be great if _HTML Clock_ can somehow include this feature.
The easiest way could be adding a configuration option on its own or in "Calendar view" to launch the _Kalendar_ app instead of displaying the default calendar popup.
Of course, the ideal solution would be, if possible, to integrate this feature like the _EventCalendar_ plasmoid.

**Comment by MarcinOrlowski** [comment]
I am sorry but that's not going to happen. The amount of work needed to have this implemented exceeds what I am planning to invest in this plasmoid in foreseeable future. Sorry.

**Comment by Sadi58** [comment]
@MarcinOrlowski I thought at least enabling an option to launch Kalendar app instead of displaying a blank calendar on clicking the plasmoid wouldn't require much effort, but if does, I fully understand you...

**Comment by MarcinOrlowski** [comment]
Should be doable. Added #73  for this.
