### ISSUE TITLE
Shared Layouts?

### ISSUE THREAD

**Issue by levone1** [MarcinOrlowski/html-clock-plasmoid#78]
Hi.  Love the widget...  I clicked on "Share Your Layout", thinking that might take me to a page of a collection of shared layouts, but it just took me to a "new issue" page...  Is there any collection of shared users' layouts?  I had considered sharing mine, but I thought surely there are some more expert ones out there...

Anyway, thanks again

**Comment by MarcinOrlowski** [comment]
Currently all user contributed layouts end up in [dedicated "Discussion" thread](https://github.com/MarcinOrlowski/html-clock-plasmoid/discussions/categories/html-clock-templates). Feel free post yours (please include the screenshot of the widget with your layout applied).
