### ISSUE TITLE
kde clock - green segment 14 font

### ISSUE THREAD

**Issue by weedmic** [MarcinOrlowski/html-clock-plasmoid#84]
Past this:

''' <!DOCTYPE html>

<html>

<body lang="en-UK" dir="ltr">

<p style="line-height: 100%; margin-bottom: 0cm; background: #4b4b4b; font-size: 30px"><font color="#00d250"><span font face="Segment14">{hh}<font face="DejaVuSans">:<font face="Segment14">{ii}<font face="DejaVuSans">:<font face="Segment14">{ss}</font></font></font></font></span></font></p>

</body>

</html>
'''

![image](https://github.com/MarcinOrlowski/html-clock-plasmoid/assets/87984287/2288973d-1ab2-4ec2-9dc7-28b329244354)

**Comment by weedmic** [comment]
When I have time, I'm going to try it with a style sheet and hopefully get the : to blink.

**Comment by MarcinOrlowski** [comment]
Hi, thanks for the input. Please feel free to share your future layouts [here](https://github.com/MarcinOrlowski/html-clock-plasmoid/discussions/categories/html-clock-templates)
