### ISSUE TITLE
Location of user layout?

### ISSUE THREAD

**Issue by Inu90** [MarcinOrlowski/html-clock-plasmoid#94]
What is the on-disk location of the last used (personal) layout?. So I updated to plasma 6 earlier today and other than downgrading to 5.27, I dont seem to have a way of getting my personal layout back.
`~/.local/share/plasma/plasmoids/com.marcinorlowski.htmlclock/contents/js/layouts.js` only has the default ones, right?

**Comment by MarcinOrlowski** [comment]
The location you mentioned is just the widget, not its runtime data. Unfortunatelly I am unable to tell where do Plasma stores plasmoids data internally. I am aware of problems on Plasma 6 (#93) and I will look into it over the weekend and hopefuly will push the working update. That (hopefuly) should bring all the data back so I think my current suggestion is "hold on".

**Comment by MarcinOrlowski** [comment]
I will close this one. Please track #93 for the updates

**Comment by Inu90** [comment]
Alright, reading your reply gave me an idea to change which keywords I put on the google search which gave me [this](https://zren.github.io/kde/docs/widget/#configuration). 
so yes `~/.config/plasma-org.kde.plasma.desktop-appletsrc` does indeed contain the last used layout... along every other plasmoid you are using.
finding it was easy enough tho.
```
[Containments][26][Applets][53]
immutability=1
plugin=com.marcinorlowski.htmlclock

[Containments][26][Applets][53][Configuration]
PreloadWeight=100
popupHeight=432
popupWidth=432

[Containments][26][Applets][53][Configuration][Appearance]
customFont=Noto Sans,14,-1,0,50,0,0,0,0,0
layoutKey=system-time-short
useCustomFont=true
useUserLayout=true
widgetContainerFillHeight=true

[Containments][26][Applets][53][Configuration][ConfigDialog]
DialogHeight=673
DialogWidth=1000

[Containments][26][Applets][53][Configuration][Layout]
layout=<style type="text/css">\n.tg  {border-collapse:collapse;border-spacing:0;}\n.tg td{border-color:black;border:none;border-width:1px;font-family:Voltaire, sans-serif;font-size:13px;\n  overflow:hidden;word-break:normal;}\n.tg th{border-color:black;border:none;border-width:1px;font-family:Voltaire, sans-serif;font-size:14px;\n  font-weight:normal;overflow:hidden;padding:2px 2px;word-break:normal;}\n.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}\n</style>\n<table class="tg" style="undefined;table-layout: fixed;">\n<tbody>\n  <tr>\n    <td valign="middle" align="center" class="tg-0pky">{MM}-{d}</td>\n    <td valign="middle" align="center" class="tg-0pky" rowspan="2" style="font-size: 26px;">{kk}:{ii}</td>\n  </tr>\n  <tr>\n    <td class="tg-0pky">({DDD})</td>\n  </tr>\n</tbody>\n</table>\n
```
I'm guessing the `[26]` and `[53]` there depends on each user's config but no idea.
